// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]


use chrono::NaiveDate;
#[derive(Queryable, Debug, Identifiable)]
#[diesel(primary_key(id))]
pub struct Flora {
    pub id: i32,
    pub common_name: String,
    pub latin_name: String,
    pub blossom_season: String,
    pub planting_date: String,
    pub date_of_discovery: Option<NaiveDate>,
    pub discoverer_id: Option<i32>,
    pub flora_type: String,
}

